#!/bin/bash

if [ $# -lt 2 ]; then
    echo "Usage:"
    echo "  $(basename $0) [File name] [File size (in Gigabytes]"
    exit 1
fi

NAME=$1
SIZE=$2

if [ -f "${NAME}" ]; then
  echo "File \"${NAME}\" already exists." 2>&1
  exit 2
fi

ionice -c idle sh -c "dd bs=1G count=${SIZE} if=/dev/zero | pv -pterabT --size ${SIZE}G | dd of=${NAME}"
