#!/bin/bash

if [ $# -lt 3 ]; then
    echo "Usage:"
    echo "  $(basename $0) [Process command line] [Check interval (seconds)] [Notification timeout (milliseconds)]"
    exit 1
fi

INTERVAL=$2
PROCESS=$1
TIMEOUT=$3

command -v notify-send &> /dev/null || sudo apt install -y libnotify-bin || exit $?

function notify {
    notify-send --expire-time=${TIMEOUT} --icon=applications-system "Process Sentinel" "$1"
    echo "$1"
}

echo "Checking for \"${PROCESS}\" started..."

FOUND=false

while true; do
    ps aux | grep ${PROCESS} | grep -v grep | grep -v $(basename $0) &> /dev/null
    [ $? -eq 0 ] && EXISTS=true || EXISTS=false

    if ! ${FOUND}; then
        if ${EXISTS}; then
            FOUND=true
            notify "\"${PROCESS}\" is running."
        fi
    else
        if ! ${EXISTS}; then
            FOUND=false
            notify "\"${PROCESS}\" terminated."
        fi
    fi

    sleep ${INTERVAL}
done