#!/bin/bash
if [ $# -lt 3 ]; then
    echo "Usage:"
    echo "  $(basename $0) [Process name] [Check interval (seconds)] [Notification timeout (milliseconds)]"
    exit 1
fi

INTERVAL=$2
PROCESS=$1
TIMEOUT=$3

command -v notify-send &> /dev/null || sudo apt install -y libnotify-bin || exit $?

function notify {
    notify-send --expire-time=${TIMEOUT} --icon=applications-system "Process Check" $1
    echo $1
}

FOUND=false

while true; do
    PID=$(pidof -s ${PROCESS})

    if ! ${FOUND}; then
        if [[ -n ${PID} ]]; then
            FOUND=true
            notify "Found!"
        fi
    else
        if [[ -z ${PID} ]]; then
            FOUND=false
            notify "Terminated."
        fi
    fi

    sleep ${INTERVAL}
done